version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=defaultdb
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api-django:
    image: django_api:${VERSION-latest}
    build:
      context: .
      dockerfile: django_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 5000:5000
    command: echo "command not specified"

  api-flask:
    image: flask_api:${VERSION-latest}
    build:
      context: .
      dockerfile: flask_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 6000:5000
    command: echo "command not specified"
  
  api-fastapi:
    image: fastapi_api:${VERSION-latest}
    build:
      context: .
      dockerfile: fastapi_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 7000:7000
    command: echo "command not specified"
  
  api-graphql:
    image: graphql_api:${VERSION-latest}
    build:
      context: .
      dockerfile: graphql_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    command: echo "command not specified"


volumes:
  pgdata:
