version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=defaultdb
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  django_api:
    image: django_api:${VERSION-latest}
    build:
      context: .
      dockerfile: django_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    command: echo "command not specified"

  flask_api:
    image: flask_api:${VERSION-latest}
    build:
      context: .
      dockerfile: flask_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 6000:6000
    depends_on:
      - db
    command: echo "command not specified"
  
  fastapi_api:
    image: fastapi_api:${VERSION-latest}
    build:
      context: .
      dockerfile: fastapi_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 7000:7000
    depends_on:
      - db
    command: ["uvicorn", "fastapi_api.main:app", "--host", "0.0.0.0", "--port", "7000", "--reload"]
  
  graphql_api:
    image: graphql_api:${VERSION-latest}
    build:
      context: .
      dockerfile: graphql_api/Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ["python", "graphql_api/main.py"]


volumes:
  pgdata:
