name: "Build and tests applications"

on:
  pull_request:
    branches:
      - main

jobs:

  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        appName: ['fastapi_api', 'graphql_api']
    
    steps:

      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker-compose build ${{ matrix.appName }}
      
      - name: Check the code
        run: docker-compose run ${{ matrix.appName }} bash lint.sh ${{ matrix.appName }}

      - name: Run database for tests
        run: docker-compose up -d db && sleep 5

      - name: Run tests
        run: docker-compose run ${{ matrix.appName }} pytest -v ${{ matrix.appName }}/tests/.
