name: "Build and tests applications"

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/apis.yml'
      - 'APIs/**'

jobs:

  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        appName: ['fastapi_api']
    
    steps:
      - name: Build docker image
        run: docker-compose build ${{ matrix.appName }}
      
      - name: Check the code
        run: docker-compose run ${{ matrix.appName }} bash lint.sh
